# Generated by Django 4.1.3 on 2022-11-14 23:06

import django.db.models.deletion
from django.db import migrations, models

import apps.contacts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=20)),
                ("birthday", models.DateField(blank=True, default=None, null=True)),
                ("is_auto_generated", models.BooleanField(default=False)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("edition_date", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=apps.contacts.models.get_icon_path
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="contacts.group",
                    ),
                ),
            ],
        ),
    ]
