# Generated by Django 4.1.3 on 2022-11-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contacts",
            options={"ordering": ["-creation_date"], "verbose_name": "Contact", "verbose_name_plural": "Contacts"},
        ),
    ]
