# Generated by Django 4.1.4 on 2022-12-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sessions_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visithandler",
            options={"ordering": ["-last_visit_at"], "verbose_name": "Visit Info"},
        ),
    ]
