# Generated by Django 4.1.4 on 2022-12-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sessions_app", "0002_alter_visithandler_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visithandler",
            options={"ordering": ["-last_visit_at"], "verbose_name": "Visit Info", "verbose_name_plural": "Visit Info"},
        ),
    ]
